[server]
keystorePath = "./cert/certificate.pfx"
superserviceID = "_auto_generated_ID_" #default: ""
ssl = false #if use HTTPS
port = 12076 #default: 3000, port of server
numberOfProcess = 4 #default: 1
enableWebTransport = false #default: false.

[cluster]
name = "owt-cluster"

[rabbit]
host = "rabbit.mcu.xiyan.com" #default: "localhost"
port = 15678 #default: 15672

[mongo]
dataBaseURL = "localhost:37017/owtdb" #default: "localhost/owtdb"
